#!/bin/bash

~/blog/src/scripts/replace


cd ~/blog/
# git pull origin master
git add .
git commit -m '...'
git push origin master

cd /var/www/blog/
# git pull origin master
git add .
git commit -m '...'
git push origin master

