#!/bin/bash

~/blog/src/scripts/replace

cd ~/Documents/blog/
# git pull origin master
git add .
git commit -m '...'
git push origin master


cd ~/blog/
# git pull origin master
git add .
git commit -m '...'
git push origin master



