#!/usr/bin/env python
#coding:utf-8
#Copyright (C) Bear Arpher

import os, fnmatch
import re

site_base = 'https://arphercn.github.io/'
site_code = 'https://github.com/arphercn/blog/blob/master/'
root_org  = '/home/arpher/blog/'
root_html = '/home/arpher/Documents/blog/'

# format href="./bbbb"
# pat_link  = re.compile(r'href="\./([\w\.-]+)"')
# format href="bbbb"
pat_link  = re.compile(r'href="([\w\.-]+)"')


# https://stackoverflow.com/questions/4205854/python-way-to-recursively-find-and-replace-string-in-text-files
# def findReplace(directory, find, replace, filePattern):
#     for path, dirs, files in os.walk(os.path.abspath(directory)):
#         for filename in fnmatch.filter(files, filePattern):
#             filepath = os.path.join(path, filename)
#             with open(filepath) as f:
#                 s = f.read()
#             s = s.replace(find, replace)
#             with open(filepath, "w") as f:
#                 f.write(s)

# findReplace(root_html, root_html, site_base, '*.html')


# str = 'src="./bbbb.jpg" cd lalala href="./xyz.php" eee href="./factory"'
# print re.sub(r'href="\./([\w\.-]+)"', 'href="' + site_base + r'\1' + '"', str)
# 编译它来提升性能 http://python3-cookbook.readthedocs.io/zh_CN/latest/c02/p05_search_and_replace_text.html
# pat_link = re.compile(r'href="\./([\w\.-]+)"')
# print pat_link.sub('href="' + site_code + r'\1' + '"', str)

for path, dirs, files in os.walk(os.path.abspath(root_html)):
    for filename in fnmatch.filter(files, '*.html'):
        filepath = os.path.join(path, filename)
        with open(filepath) as f:
            s = f.read()
        s = s.replace(root_org, site_base)
        s = pat_link.sub('target="_blank" href="' + path + '/' + r'\1' + '"', s)
        s = s.replace(root_html, site_code)
        with open(filepath, "w") as f:
            f.write(s)